// SPDX-License-Identifier: GPL-3.0-or-later
#include <atlas/platform/key.hpp>

#include "sdl_keymap.hpp"
#include <SDL3/SDL_scancode.h>
#include <catch2/catch_test_macros.hpp>

#include <cstdint>
#include <set>

using atlas::platform::Key;
using atlas::platform::to_string;
using atlas::platform::detail::from_sdl_scancode;
using atlas::platform::detail::to_sdl_scancode;

TEST_CASE("every key maps to a scancode", "[platform][keymap]") {
    // A key missing from the table is a key that silently does nothing. That is a miserable
    // bug to track down from the outside, so it is caught here instead.
    for (std::uint16_t i = 1; i < static_cast<std::uint16_t>(Key::Count); ++i) {
        const auto key = static_cast<Key>(i);
        INFO("key " << to_string(key));
        CHECK(to_sdl_scancode(key) != SDL_SCANCODE_UNKNOWN);
    }
}

TEST_CASE("the mapping round-trips in both directions", "[platform][keymap]") {
    for (std::uint16_t i = 1; i < static_cast<std::uint16_t>(Key::Count); ++i) {
        const auto key = static_cast<Key>(i);
        INFO("key " << to_string(key));
        CHECK(from_sdl_scancode(to_sdl_scancode(key)) == key);
    }
}

TEST_CASE("no two keys share a scancode", "[platform][keymap]") {
    // A duplicate would make the reverse mapping ambiguous, and one of the two keys would
    // quietly become unreachable.
    std::set<SDL_Scancode> seen;
    for (std::uint16_t i = 1; i < static_cast<std::uint16_t>(Key::Count); ++i) {
        const auto key = static_cast<Key>(i);
        INFO("key " << to_string(key));
        CHECK(seen.insert(to_sdl_scancode(key)).second);
    }
}

TEST_CASE("the sentinels map to nothing", "[platform][keymap]") {
    CHECK(to_sdl_scancode(Key::Unknown) == SDL_SCANCODE_UNKNOWN);
    CHECK(to_sdl_scancode(Key::Count) == SDL_SCANCODE_UNKNOWN);
    CHECK(from_sdl_scancode(SDL_SCANCODE_UNKNOWN) == Key::Unknown);
}

TEST_CASE("a scancode Atlas does not model maps to Unknown", "[platform][keymap]") {
    // Atlas models a deliberately small subset. Anything outside it must come back as
    // Unknown rather than as an arbitrary key.
    CHECK(from_sdl_scancode(SDL_SCANCODE_KP_PLUS) == Key::Unknown);
    CHECK(from_sdl_scancode(SDL_SCANCODE_SCROLLLOCK) == Key::Unknown);
}

TEST_CASE("a few mappings are what a reader would expect", "[platform][keymap]") {
    // Spot checks, so that a table generated by a script is still verified by a human
    // expectation rather than only against itself.
    CHECK(to_sdl_scancode(Key::A) == SDL_SCANCODE_A);
    CHECK(to_sdl_scancode(Key::Num0) == SDL_SCANCODE_0);
    CHECK(to_sdl_scancode(Key::Escape) == SDL_SCANCODE_ESCAPE);
    CHECK(to_sdl_scancode(Key::Enter) == SDL_SCANCODE_RETURN);
    CHECK(to_sdl_scancode(Key::LeftSuper) == SDL_SCANCODE_LGUI);
    CHECK(to_sdl_scancode(Key::F12) == SDL_SCANCODE_F12);
}
