// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generated by tools/cook_shaders.py. Do not edit.
//
// Resource counts are read out of the compiled shaders by reflection, so they
// cannot disagree with the shaders they describe.
#pragma once

#include <cstdint>
#include <string_view>

namespace atlas::shaders {

struct ShaderInfo {
    std::string_view name;
    std::string_view stage;            ///< "vertex" or "fragment"
    std::string_view spirv_file;
    std::string_view spirv_entry_point;
    std::string_view msl_file;
    std::string_view msl_entry_point;
    std::uint32_t samplers = 0;        ///< Sampled textures, each with its sampler
    std::uint32_t storage_textures = 0;
    std::uint32_t storage_buffers = 0;
    std::uint32_t uniform_buffers = 0;
};

inline constexpr ShaderInfo kSpriteFragment{
    .name = "sprite",
    .stage = "fragment",
    .spirv_file = "sprite.frag.spv",
    .spirv_entry_point = "main",
    .msl_file = "sprite.frag.msl",
    .msl_entry_point = "main0",
    .samplers = 1,
    .storage_textures = 0,
    .storage_buffers = 0,
    .uniform_buffers = 0,
};

inline constexpr ShaderInfo kSpriteVertex{
    .name = "sprite",
    .stage = "vertex",
    .spirv_file = "sprite.vert.spv",
    .spirv_entry_point = "main",
    .msl_file = "sprite.vert.msl",
    .msl_entry_point = "main0",
    .samplers = 0,
    .storage_textures = 0,
    .storage_buffers = 0,
    .uniform_buffers = 1,
};

inline constexpr ShaderInfo kTriangleFragment{
    .name = "triangle",
    .stage = "fragment",
    .spirv_file = "triangle.frag.spv",
    .spirv_entry_point = "main",
    .msl_file = "triangle.frag.msl",
    .msl_entry_point = "main0",
    .samplers = 0,
    .storage_textures = 0,
    .storage_buffers = 0,
    .uniform_buffers = 0,
};

inline constexpr ShaderInfo kTriangleVertex{
    .name = "triangle",
    .stage = "vertex",
    .spirv_file = "triangle.vert.spv",
    .spirv_entry_point = "main",
    .msl_file = "triangle.vert.msl",
    .msl_entry_point = "main0",
    .samplers = 0,
    .storage_textures = 0,
    .storage_buffers = 0,
    .uniform_buffers = 0,
};

/// Every cooked shader, so that one can be found by name and stage.
inline constexpr const ShaderInfo* kAll[] = {
    &kSpriteFragment,
    &kSpriteVertex,
    &kTriangleFragment,
    &kTriangleVertex,
};

}  // namespace atlas::shaders
